### PR TITLE
check for 'err' in callback and only log message on failure

### LINKED ISSUE #142: Heroku subgen logs warning which is incorrect
##### **Overview of the issue**

When trying to add the okta provisioning script to `.gitignore` the heroku subgen logs a warning it was not possible. This is wrong. The warning is logged in any case https://github.com/jhipster/generator-jhipster-micronaut/blob/123e85393c9dd774fc35dc610b82e3bd86a4bd70/generators/heroku/index.js#L132

##### **Reproduce the error**

Create an application with oauth and deploy to heroku using okta.

##### **Related issues**

None

##### **Suggest a Fix**

Checking if `err` is defined and only warn if there is a real error.

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by atomfrede**
closes #142

### CODE REVIEW

File: generators/heroku/index.js [hunk 1]
```diff
@@ -129,7 +129,9 @@ module.exports = class extends HerokuGeneratorOverride {
                 if (this.useOkta) {
                     this.template('provision-okta-addon.sh.ejs', 'provision-okta-addon.sh');
                     fs.appendFile('.gitignore', 'provision-okta-addon.sh', 'utf8', (err, data) => {
-                        this.log(`${chalk.yellow.bold('WARNING!')}Failed to add 'provision-okta-addon.sh' to .gitignore.'`);
+                        if (err) {
+                            this.log(`${chalk.yellow.bold('WARNING!')}Failed to add 'provision-okta-addon.sh' to .gitignore.'`);
```
Comment (mraible) [inline generators/heroku/index.js:133]:
```suggestion
                            this.log(`${chalk.yellow.bold('WARNING!')} Failed to add 'provision-okta-addon.sh' to .gitignore.'`);
```
